In [4]:
from pathlib import Path
import pandas as pd

In [5]:

import parsers.fastqc as fastqc

In [6]:
files = Path("/home/unicph.domain/glj523/fastq_paths_single_lib.txt").read_text().splitlines()

In [7]:
df = fastqc.get_basic_stats(files)

In [ ]:
df.to_csv("/home/unicph.domain/glj523/fastqc_basic_stats.csv", index=False)

Measure,Filename,File type,Encoding,Total Sequences,Total Bases,Sequences flagged as poor quality,Sequence length,%GC,Total Deduplicated Percentage,Basic Statistics status,Per base sequence quality status,Per tile sequence quality status,Per sequence quality scores status,Per base sequence content status,Per sequence GC content status,Per base N content status,Sequence Length Distribution status,Sequence Duplication Levels status,Overrepresented sequences status,Adapter Content status
0,Lib_LV7009021867_collapsed.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,53357894,3.7 Gbp,0,30-191,48,95.25457941435809,pass,pass,fail,pass,pass,pass,pass,warn,pass,pass,pass
1,Lib_LV7009021867_collapsed.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,53084033,3.7 Gbp,0,30-191,48,95.3009835324874,pass,pass,fail,pass,pass,pass,pass,warn,pass,pass,pass
2,Lib_LV7009021867_collapsed.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,106326331,6.9 Gbp,0,30-191,49,48.33621928858068,pass,pass,warn,pass,fail,fail,pass,warn,fail,fail,pass
3,Lib_LV7009021867_collapsed.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,47503274,3.4 Gbp,0,30-191,48,95.15055564628528,pass,pass,fail,pass,pass,pass,pass,warn,pass,pass,pass
4,Lib_LV7009021867_L001_R1.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,61102744,6.1 Gbp,0,101,56,31.917588221616388,pass,pass,pass,pass,fail,fail,pass,pass,fail,fail,fail
5,Lib_LV7009021867_L001_R2.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,61102744,6.1 Gbp,0,101,57,33.25311689346882,pass,pass,warn,pass,fail,fail,pass,pass,fail,fail,fail
6,Lib_LV7009021867_L002_R1.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,61688263,6.2 Gbp,0,101,56,31.157520409972484,pass,pass,warn,pass,fail,fail,pass,pass,fail,fail,fail
7,Lib_LV7009021867_L002_R2.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,61688263,6.2 Gbp,0,101,57,32.57474173182614,pass,pass,warn,pass,fail,fail,pass,pass,fail,fail,fail
8,Lib_LV7009021867_L003_R1.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,60567626,6.1 Gbp,0,101,56,31.846836629626925,pass,pass,warn,pass,fail,fail,pass,pass,fail,fail,fail
9,Lib_LV7009021867_L003_R2.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,60567626,6.1 Gbp,0,101,57,33.29301260546817,pass,pass,warn,pass,fail,fail,pass,pass,fail,fail,fail
10,Lib_LV7009021867_L004_R1.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,60681477,6.1 Gbp,0,101,56,31.899326031397766,pass,pass,warn,pass,fail,fail,pass,pass,fail,fail,fail
11,Lib_LV7009021867_L004_R2.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,60681477,6.1 Gbp,0,101,57,33.31199349412218,pass,pass,fail,pass,fail,fail,pass,pass,fail,fail,fail
12,Lib_LV7009021867_L001_collapsed.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,26870783,1.7 Gbp,0,30-191,49,64.57647482194025,pass,pass,fail,pass,fail,fail,pass,warn,warn,fail,pass
13,Lib_LV7009021867_L001_collapsedtrunc.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,42407,2.5 Mbp,0,30-190,47,90.71379725045394,pass,pass,fail,pass,warn,fail,warn,warn,pass,fail,pass
14,Lib_LV7009021867_L001_R1.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,5639841,569.6 Mbp,0,100-101,62,16.485611606518848,pass,pass,warn,pass,fail,fail,pass,warn,fail,fail,fail
15,Lib_LV7009021867_L001_R2.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,5639841,569.6 Mbp,0,99-101,87,19.527380125275783,pass,pass,warn,pass,fail,fail,pass,warn,fail,fail,fail
16,Lib_LV7009021867_L001_singleton.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,2192,221.3 kbp,0,98-101,88,25.593065693430656,pass,pass,fail,pass,fail,fail,warn,warn,fail,fail,fail
17,Lib_LV7009021867_L002_collapsed.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,26625066,1.7 Gbp,0,30-191,49,64.6586217586659,pass,pass,fail,pass,fail,fail,pass,warn,warn,fail,pass
18,Lib_LV7009021867_L002_collapsedtrunc.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,38455,2.3 Mbp,0,30-190,47,90.83604212716162,pass,pass,fail,pass,warn,fail,warn,warn,pass,fail,pass
19,Lib_LV7009021867_L002_R1.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,5705251,576.2 Mbp,0,100-101,62,15.64189261584304,pass,pass,warn,pass,fail,fail,pass,warn,fail,fail,fail
20,Lib_LV7009021867_L002_R2.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,5705251,576.2 Mbp,0,100-101,87,18.7830746177045,pass,pass,warn,pass,fail,fail,pass,warn,fail,fail,fail
21,Lib_LV7009021867_L002_singleton.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,2128,214.9 kbp,0,101,87,26.033834586466163,pass,pass,fail,pass,fail,fail,warn,pass,fail,fail,fail
22,Lib_LV7009021867_L003_collapsed.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,26592768,1.7 Gbp,0,30-191,49,64.84792902737072,pass,pass,fail,pass,fail,fail,pass,warn,warn,fail,pass
23,Lib_LV7009021867_L003_collapsedtrunc.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,40361,2.4 Mbp,0,30-190,47,91.32578479224995,pass,pass,fail,pass,fail,fail,warn,warn,pass,fail,pass
24,Lib_LV7009021867_L003_R1.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,5536619,559.1 Mbp,0,100-101,62,16.304543571401492,pass,pass,pass,pass,fail,fail,pass,warn,fail,fail,fail
25,Lib_LV7009021867_L003_R2.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,5536619,559.1 Mbp,0,101,87,19.37103829947544,pass,pass,warn,pass,fail,fail,pass,pass,fail,fail,fail
26,Lib_LV7009021867_L003_singleton.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,2007,202.7 kbp,0,101,87,25.85949177877429,pass,pass,fail,pass,fail,fail,warn,pass,fail,fail,fail
27,Lib_LV7009021867_L004_collapsed.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,26237714,1.7 Gbp,0,30-191,49,64.7192524297244,pass,pass,fail,pass,fail,fail,pass,warn,warn,fail,pass
28,Lib_LV7009021867_L004_collapsedtrunc.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,39732,2.4 Mbp,0,30-190,47,91.70945333736032,pass,pass,fail,pass,warn,fail,warn,warn,pass,fail,pass
29,Lib_LV7009021867_L004_R1.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,5572908,562.8 Mbp,0,100-101,62,15.864893927924259,pass,pass,warn,pass,fail,fail,pass,warn,fail,fail,fail
30,Lib_LV7009021867_L004_R2.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,5572908,562.8 Mbp,0,101,88,18.91853289560197,pass,pass,fail,pass,fail,fail,pass,pass,fail,fail,fail
31,Lib_LV7009021867_L004_singleton.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,2113,213.4 kbp,0,101,87,26.455276857548508,pass,pass,fail,pass,fail,fail,warn,pass,fail,fail,fail

In [ ]:
df.to_csv("fastqc_basic_stats_LV7009021851.tsv", index=False, sep="\t")

In [8]:
merge_lanes['modules']['Basic Statistics']

{'status': 'pass',
 'header_values': {},
 'table': {'headers': ['Measure', 'Value'],
  'rows': [{'Measure': 'Filename',
    'Value': 'Lib_LV7008864206_collapsed.fastq.gz'},
   {'Measure': 'File type', 'Value': 'Conventional base calls'},
   {'Measure': 'Encoding', 'Value': 'Sanger / Illumina 1.9'},
   {'Measure': 'Total Sequences', 'Value': '188989298'},
   {'Measure': 'Total Bases', 'Value': '11 Gbp'},
   {'Measure': 'Sequences flagged as poor quality', 'Value': '0'},
   {'Measure': 'Sequence length', 'Value': '30-191'},
   {'Measure': '%GC', 'Value': '60'}]}}

In [36]:
def get_basic_stats(results) -> pd.DataFrame:
    combined_df = pd.DataFrame()
    for result in results:
        status_data = [{'Measure': f"{k} status", 'Value': v['status']} for k, v in result['modules'].items()]
        basic_stats = result['modules']['Basic Statistics']['table']['rows']
        header_data = [{'Measure': i, 'Value': j} for k, v in result['modules'].items() for i, j in v['header_values'].items()]
        df = pd.DataFrame(basic_stats + header_data + status_data)
        df = df.set_index('Measure').T.reset_index(drop=True)
        combined_df = pd.concat([combined_df, df], ignore_index=True)
    return combined_df

In [38]:
res

Measure,Filename,File type,Encoding,Total Sequences,Total Bases,Sequences flagged as poor quality,Sequence length,%GC,Total Deduplicated Percentage,Basic Statistics status,Per base sequence quality status,Per tile sequence quality status,Per sequence quality scores status,Per base sequence content status,Per sequence GC content status,Per base N content status,Sequence Length Distribution status,Sequence Duplication Levels status,Overrepresented sequences status,Adapter Content status
0,Lib_LV7008864206_L001_collapsed.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,46694974,2.7 Gbp,0,30-191,60,73.97223323811349,pass,pass,fail,pass,warn,fail,pass,warn,pass,pass,pass
1,Lib_LV7008864206_collapsed.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,188989298,11 Gbp,0,30-191,60,44.66736217565382,pass,pass,fail,pass,warn,fail,pass,warn,fail,pass,pass

In [35]:
def combine_basic_stats(*results) -> pd.DataFrame:
    dfs = [get_basic_stats(result) for result in results]
    combined_df = pd.concat(dfs, ignore_index=True)
    return combined_df

In [34]:
res

Measure,Filename,File type,Encoding,Total Sequences,Total Bases,Sequences flagged as poor quality,Sequence length,%GC,Total Deduplicated Percentage,Basic Statistics status,Per base sequence quality status,Per tile sequence quality status,Per sequence quality scores status,Per base sequence content status,Per sequence GC content status,Per base N content status,Sequence Length Distribution status,Sequence Duplication Levels status,Overrepresented sequences status,Adapter Content status
0,Lib_LV7008864206_L001_collapsed.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,46694974,2.7 Gbp,0,30-191,60,73.97223323811349,pass,pass,fail,pass,warn,fail,pass,warn,pass,pass,pass

In [27]:
res

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,"{'Measure': 'Basic Statistics status', 'Value'...",{'Measure': 'Per base sequence quality status'...,{'Measure': 'Per tile sequence quality status'...,{'Measure': 'Per sequence quality scores statu...,{'Measure': 'Per base sequence content status'...,"{'Measure': 'Per sequence GC content status', ...","{'Measure': 'Per base N content status', 'Valu...",{'Measure': 'Sequence Length Distribution stat...,{'Measure': 'Sequence Duplication Levels statu...,{'Measure': 'Overrepresented sequences status'...,"{'Measure': 'Adapter Content status', 'Value':...","{'Measure': 'Filename', 'Value': 'Lib_LV700886...","{'Measure': 'File type', 'Value': 'Conventiona...","{'Measure': 'Encoding', 'Value': 'Sanger / Ill...","{'Measure': 'Total Sequences', 'Value': '18898...","{'Measure': 'Total Bases', 'Value': '11 Gbp'}",{'Measure': 'Sequences flagged as poor quality...,"{'Measure': 'Sequence length', 'Value': '30-191'}","{'Measure': '%GC', 'Value': '60'}","{'Measure': 'Total Deduplicated Percentage', '..."
1,"{'Measure': 'Basic Statistics status', 'Value'...",{'Measure': 'Per base sequence quality status'...,{'Measure': 'Per tile sequence quality status'...,{'Measure': 'Per sequence quality scores statu...,{'Measure': 'Per base sequence content status'...,"{'Measure': 'Per sequence GC content status', ...","{'Measure': 'Per base N content status', 'Valu...",{'Measure': 'Sequence Length Distribution stat...,{'Measure': 'Sequence Duplication Levels statu...,{'Measure': 'Overrepresented sequences status'...,"{'Measure': 'Adapter Content status', 'Value':...","{'Measure': 'Filename', 'Value': 'Lib_LV700886...","{'Measure': 'File type', 'Value': 'Conventiona...","{'Measure': 'Encoding', 'Value': 'Sanger / Ill...","{'Measure': 'Total Sequences', 'Value': '46694...","{'Measure': 'Total Bases', 'Value': '2.7 Gbp'}",{'Measure': 'Sequences flagged as poor quality...,"{'Measure': 'Sequence length', 'Value': '30-191'}","{'Measure': '%GC', 'Value': '60'}","{'Measure': 'Total Deduplicated Percentage', '..."

In [14]:
res

Measure,Basic Statistics status,Per base sequence quality status,Per tile sequence quality status,Per sequence quality scores status,Per base sequence content status,Per sequence GC content status,Per base N content status,Sequence Length Distribution status,Sequence Duplication Levels status,Overrepresented sequences status,Adapter Content status,Filename,File type,Encoding,Total Sequences,Total Bases,Sequences flagged as poor quality,Sequence length,%GC,Total Deduplicated Percentage
0,pass,pass,fail,pass,warn,fail,pass,warn,fail,pass,pass,Lib_LV7008864206_collapsed.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,188989298,11 Gbp,0,30-191,60,44.66736217565382

In [218]:
pd.concat([get_basic_stats(merge_lanes), get_basic_stats(trim_l1)])

Measure,Filename,File type,Encoding,Total Sequences,Total Bases,Sequences flagged as poor quality,Sequence length,%GC,Total Deduplicated Percentage,Basic Statistics status,Per base sequence quality status,Per tile sequence quality status,Per sequence quality scores status,Per base sequence content status,Per sequence GC content status,Per base N content status,Sequence Length Distribution status,Sequence Duplication Levels status,Overrepresented sequences status,Adapter Content status
0,Lib_LV7008864206_collapsed.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,188989298,11 Gbp,0,30-191,60,73.97223323811349,pass,pass,fail,pass,warn,fail,pass,warn,fail,pass,pass
0,Lib_LV7008864206_L001_collapsed.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,46694974,2.7 Gbp,0,30-191,60,73.97223323811349,pass,pass,fail,pass,warn,fail,pass,warn,pass,pass,pass